# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('education', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('G', 'Graduate'), ('P', 'Professor')], max_length=1)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(choices=[('R1B1', 'R1B1'), ('R2B1', 'R2B1'), ('R3B1', 'R3B1'), ('R1B2', 'R1B2'), ('R2B2', 'R2B2'), ('R3B2', 'R3B2'), ('R1B3', 'R1B3'), ('R2B3', 'R2B3'), ('R3B3', 'R3B3')], max_length=4)),
                ('values', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
