# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='values',
        ),
    ]
