# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_remove_office_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='values',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
