# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0004_auto_20170810_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='values',
            new_name='R1B1v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='space',
        ),
        migrations.AddField(
            model_name='office',
            name='R1B1',
            field=models.CharField(default='R1B1', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R1B2',
            field=models.CharField(default='R1B2', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R1B2v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R1B3',
            field=models.CharField(default='R1B3', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R1B3v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B1',
            field=models.CharField(default='R2B1', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B1v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B2',
            field=models.CharField(default='R2B2', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B2v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B3',
            field=models.CharField(default='R2B3', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B3v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B1',
            field=models.CharField(default='R3B1', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B1v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B2',
            field=models.CharField(default='R3B2', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B2v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B3',
            field=models.CharField(default='R3B3', max_length=4),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B3v',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
