# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_auto_20170814_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='R1B1v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R1B2v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R1B3v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R2B1v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R2B2v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R2B3v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R3B1v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R3B2v',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R3B3v',
        ),
        migrations.AlterField(
            model_name='office',
            name='R1B1',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R1B2',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R1B3',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R2B1',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R2B2',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R2B3',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R3B1',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R3B2',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='office',
            name='R3B3',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
