# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0006_auto_20170814_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='R1B2',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R1B3',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R2B1',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R2B2',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R2B3',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R3B1',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R3B2',
        ),
        migrations.RemoveField(
            model_name='office',
            name='R3B3',
        ),
    ]
