# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0007_auto_20170814_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='R1B2',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R1B3',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B1',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B2',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R2B3',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B1',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B2',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='office',
            name='R3B3',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
